name: Test SQL Server on GitHub Action

on:
  push:
    branches: ["master"]
jobs:
  inspect:
    name: Inspect SQL Server ${{ matrix.version }}
    runs-on: windows-2025
    environment: dev
    strategy:
      fail-fast: false
      matrix:
        version: ['2008','2012','2014','2016','2017','2019']
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - uses: ariga/setup-atlas@master
      with:
        cloud-token: ${{ secrets.ATLAS_TOKEN }}
    - run:
        atlas version
    - uses: tediousjs/setup-sqlserver@v2
      with:
        sqlserver-version: ${{ matrix.version }}
        skip-os-check: true
        wait-for-ready: true
        install-updates: true
        sa-password: 'P@ssw0rd0995'
    - run:
        atlas schema inspect --url='sqlserver://sa:P%40ssw0rd0995@localhost:1433/master'
