name: Test SQL Server on GitHub Action

on:
  push:
    branches: ["master"]
jobs:
  build-and-deploy:
    runs-on: windows-2022
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - uses: tediousjs/setup-sqlserver@v2
      with:
        skip-os-check: false
        sqlserver-version: '2016'
        native-client-version: ''
        odbc-version: ''
        sa-password: 'yourStrong(!)Password'
        db-collation: 'SQL_Latin1_General_CP1_CI_AS'
        install-arguments: ''
        wait-for-ready: true
        install-updates: false
