name: Test SQL Server on GitHub Action

on:
  push:
    branches: ["master"]
jobs:
  build-and-deploy:
    runs-on: windows-2022
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - uses: ariga/setup-atlas@master
      with:
        cloud-token: ${{ secrets.ATLAS_TOKEN }}
    - run:
        atlas version
    - uses: tediousjs/setup-sqlserver@v2
      with:
        sqlserver-version: '2016'
        skip-os-check: true
        wait-for-ready: true
        install-updates: true
        sa-password: 'P@ssw0rd0995'
    - run:
        atlas schema inspect --url='sqlserver://sa:P%40ssw0rd0995@localhost:1433/master'
